### ISSUE TITLE
Unable to add or update languages

### ISSUE THREAD

**Issue by ezeveliz** [Laravel-Lang/publisher#179]
- Lang Publisher Version: 11.1.4
- Lang Lang Version: 10.1.11
- Laravel Version: 8.74.0
- PHP Version: 8.1.0

### Description:
Upon trying to add a language, the following legend shows: "Could not find plugins available for processing". The same occurs when using lang:update(I had the assets from a previous version).

### Steps To Reproduce:
1. Attempt to install a language or update a previous one

**Comment by andrey-helldar** [comment]
Sorry, there was a collision. I'll fix it now :)

**Comment by ezeveliz** [comment]
Thx for the quick reply!

**Comment by andrey-helldar** [comment]
Version [`11.1.5`](https://github.com/Laravel-Lang/publisher/releases/tag/v11.1.5) has been released.

Let me remind you that since version `11.0`, the [publisher](https://github.com/Laravel-Lang/publisher) does not require [`laravel-lang/lang`](https://github.com/Laravel-Lang/lang) package by default.

For it to work, you need to install the package manually:

```php
composer require laravel-lang/publisher laravel-lang/lang
```
